### ISSUE TITLE
error: Gem cmd is not installed

### ISSUE THREAD

**Issue by galenyuan** [sindresorhus/gulp-ruby-sass#235]
I try to compile sass to css but it alert error

Gem cmd is not installed

I have installed ruby and after alert I try "gem install cmd"
but it still alert error, can u help to fix it?

**Comment by arthurvr** [comment]
I guess something went wrong while installing the Sass gem. What does `sass --version` output?

**Comment by galenyuan** [comment]
in fact, sass work well in other side, I can compile sass in cmd, but it can't work in gulp plusin

**Comment by vydimitrov** [comment]
I came across the same issue. The "sass -v" command ouput - "Sass 3.4.16 (Selective Steve)"

**Comment by robwierzbowski** [comment]
I haven't been able to reproduce this. I think @arthurvr is probably right; can you try uninstalling Sass and re-installing to see if the problem persists?

**Comment by oneseven** [comment]
Oh, just open another issue, I met this too, not able to solve it this moment. anyone know the reason?

**Comment by oneseven** [comment]
@robwierzbowski 
I tried your suggestion, uninstall it and re-install , problem persists.

**Comment by vydimitrov** [comment]
@robwierzbowski,
Sorry, I did not have time to try this ... I will do my best to try it tomorrow and I'll let you know the results. I hope it works ... it seems that it did help @oneseven. 

Thanks,

**Comment by robwierzbowski** [comment]
Also information on your environment would be helpful (operating system, gulp version, anything else you think may be pertinent).

**Comment by oneseven** [comment]
Win7 64 bit, gulp are installed with latest version yesterday.

**Comment by oneseven** [comment]
gulp [09:15:39] CLI version 3.9.0
Sass 3.4.16 (Selective Steve)

**Comment by galenyuan** [comment]
@all I have fixed it with re-install ruby,sass and gulp : )

**Comment by robwierzbowski** [comment]
Awesome! Yeah that was a really weird error.

On Sunday, August 16, 2015, Galen <notifications@github.com> wrote:

> @all <https://github.com/all> I have fixed it with re-install ruby,sass
> and gulp : )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/235#issuecomment-131648723>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by galenyuan** [comment]
@robwierzbowski in fact, I still can't find the reason, maybe something wrong with gulp call sass/ruby : )

**Comment by oneseven** [comment]
@galenyuan 
Not work for my local env

I tried uninstall ruby, gulp, sass, and reinstall ruby, sass, and gulp, but still, same error.

Paste my gulp.js for reference

                // Introduce Gulp
		var gulp = require('gulp'); 

		// Introduce Plugin
		var sass = require('gulp-ruby-sass');


		gulp.task('sass', function() {
		    return sass('src/theme-all.scss')
		        .on('error', function (err) { console.error('Error!',err.message); })
		        .pipe(gulp.dest('./dist'));
		});


		gulp.task('watch', function() {
		    gulp.watch('src/theme-all.scss',['sass']);
		});

		gulp.task('default',['sass','watch']);

**Comment by oneseven** [comment]
My Issue finally fixed after 2 times reinstall.

If anyone still met this issue please try below:
When you install the ruby with  Ruby installer, do not check the option to assist the path set up, but manually add it yourself to system variable.
Reinstall SASS & gulp afterwards, and retry!

**Comment by galenyuan** [comment]
congratulations @oneseven

**Comment by oneseven** [comment]
@galenyuan  Thanks.

**Comment by robwierzbowski** [comment]
Looks like everyone's issues are resolved. Thank you for posting your solutions in case anyone else has this issue.

Closing!

**Comment by mochawich** [comment]
In case anyone is still having this issue, make sure that your `Path` includes:
`C:\Windows\System32`
Obviously, ruby bin directory should be included as well. For example:
`C:\Ruby22\bin`

**Comment by tavisca-dpingale** [comment]
I am totally new and was total blank on this issue.Thanks the last solution works for me
